<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 2</b> 
    
Great, Yonas! You've done a great job on all the comments and now your project has been accepted.
    
Thank you for your work and I wish you success in the following projects!

<div class="alert alert-warning"; style="border-left: 7px solid gold">
<b>⚠️ Reviewer's comment, v. 2</b> 

Below I will recommend you one source that will help you with some new techniques in data analysis in python:    
    
* [Kaggle](https://www.kaggle.com/code/parulpandey/10-simple-hacks-to-speed-up-your-data-analysis)

<div style="border:solid blue 2px; padding: 20px">
  
**Hello Yonas**

I am happy to review your project today!

You will find my comments in coloured cells marked as 'Reviewer's comment'. The cell colour will vary based on the contents - I am explaining it further below. 

**Note:** Please do not remove or change my comments - they will help me in my future reviews and will make the process smoother for both of us. 

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment</b> 
    
Such comment will mark efficient solutions and good ideas that can be used in other projects.
</div>

<div class="alert alert-warning"; style="border-left: 7px solid gold">
<b>⚠️ Reviewer's comment</b> 
    
The parts marked with yellow comments indicate that there is room for optimisation. Though the correction is not necessary it is good if you implement it.
</div>

<div class="alert alert-danger"; style="border-left: 7px solid red">
<b>⛔️ Reviewer's comment</b> 
    
If you see such a comment, it means that there is a problem that needs to be fixed. Please note that I won't be able to accept your project until the issue is resolved.
</div>

You are also very welcome to leave your comments / describe the corrections you've done / ask me questions, marking them with a different colour. You can use the example below: 

<div class="alert alert-info"; style="border-left: 7px solid blue">
<b>Student's comment</b>

<div style="border:solid green 2px; padding: 20px">
    
<div class="alert alert-success">
<b>Review summary</b> 
    
Yonas, thanks for submitting the project. You've done a very good job and I enjoyed reviewing it.
    
- You completed all the tasks.
- Your code was optimal and easy to read. 
- You wrote your own functions.
    
There are only a few critical comments that need to be corrected. You will find them in the red-colored cells in relevant sections. You may also work on the yellow comments. If you have any questions please write them when you return your project. 
    
I'll be looking forward to getting your updated notebook.

<div class="alert alert-danger"; style="border-left: 7px solid red">
<b>⛔️ Reviewer's comment, v. 1</b> 
    
Before sending a new version, please click `Kernel - > Restart & Run all` to make sure that your code is working

# Project: Data Analysis with Pandas

In this project, you will work with a dataset containing information about movies and shows. You will use the pandas library to read, clean, and analyze the data. This project will help you practice working with DataFrames, indexing, and data manipulation using pandas.


## Dataset Description

The dataset `movies_and_shows.csv` contains information about various movies and shows, including:

- **name**: The name of the actor or actress.
- **Character**: The character they played.
- **r0le**: The role type (e.g., ACTOR).
- **TITLE**: The title of the movie or show.
- **Type**: Whether it's a MOVIE or SHOW.
- **release Year**: The year it was released.
- **genres**: A list of genres the movie or show belongs to.
- **imdb sc0re**: The IMDb score of the movie or show.
- **imdb v0tes**: The number of votes on IMDb.

Here's a small sample of the dataset:

| name              | Character                         | r0le   | TITLE        |  Type | release Year | genres             | imdb sc0re | imdb v0tes |
|-------------------|-----------------------------------|--------|--------------|-------|--------------|--------------------|------------|------------|
| Robert De Niro    | Travis Bickle                     | ACTOR  | Taxi Driver  | MOVIE | 1976         | ['drama', 'crime'] | 8.2        | 808582     |
| Jodie Foster      | Iris Steensma                     | ACTOR  | Taxi Driver  | MOVIE | 1976         | ['drama', 'crime'] | 8.2        | 808582     |
| Albert Brooks     | Tom                               | ACTOR  | Taxi Driver  | MOVIE | 1976         | ['drama', 'crime'] | 8.2        | 808582     |
| Harvey Keitel     | Matthew 'Sport' Higgins           | ACTOR  | Taxi Driver  | MOVIE | 1976         | ['drama', 'crime'] | 8.2        | 808582     |
| Cybill Shepherd   | Betsy                             | ACTOR  | Taxi Driver  | MOVIE | 1976         | ['drama', 'crime'] | 8.2        | 808582     |

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 1</b> 
    
Title and introduction are essential parts of the project. Make sure you do not forget to include it in your further projects. 
    
It is optimal if introduction consists of:
    
- brief description of the situation;
- goal of the project;
- description of the data we are going to use.
</div>

## Getting Started

Let's begin by setting up our environment.

### Importing Libraries

First, we need to import the necessary libraries.

**Instructions:**

- Import the `pandas` library, which we will use for data manipulation.

In [1]:
import pandas as pd #Import the pandas library as 'pd'

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 1</b> Needed library has been added </div>

We will load the dataset into a pandas DataFrame to begin our analysis.

**Instructions:**

- Read the `movies_and_shows.csv` file into a DataFrame. It is in the /datasets directory so the full path to include in the read_csv method will be "/datasets/movies_and_shows.csv"
- Display the first few rows of the DataFrame to get an initial look at the data.

**Hints:**

- Use `pd.read_csv()` to read the CSV file and store it in a variable called "df".
- Use the `.head()` method to display the first few rows.

In [2]:
df = pd.read_csv('/datasets/movies_and_shows.csv')# Read the dataset into a DataFrame

In [3]:
# Display the first few rows of the DataFrame
df.head()

,name,Character,r0le,TITLE,Type,release Year,genres,imdb sc0re,imdb v0tes
0,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
1,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
2,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
3,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
4,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0

Understanding the structure and content of your data is crucial before performing any analysis.

**Instructions:**

- Use the `.info()` method to get information about the DataFrame.
- Identify any issues with the Column names.

In [4]:
print(df.info())# Get information about the DataFrame and print the column names

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85579 entries, 0 to 85578
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0      name       85579 non-null  object
 1   Character     85579 non-null  object
 2   r0le          85579 non-null  object
 3   TITLE         85578 non-null  object
 4     Type        85579 non-null  object
 5   release Year  85579 non-null  int64
 6   genres        85579 non-null  object
 7   imdb sc0re    80970 non-null  float64
 8   imdb v0tes    80853 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 5.9+ MB
None

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 1</b> 
    
Great - you've used a comprehensive set of methods to have a first look at the data.

## Task 1: Data Cleaning

Let's clean the data to fix issues with the column names

**Instructions:**
- Rename the columns to correct any errors and make them consistent.

**Hints:**

- Use the `.rename()` method to rename columns.
- Pass a dictionary to the `columns` parameter of `.rename()`, where the keys are the old column names and the values are the new names.
- Remove unnecessary whitespace from the column names.

In [5]:
new_column_names = {
    'name': 'name',
    'Character': 'character',
    'r0le': 'role',
    'TITLE': 'title',
    '  Type': 'type',
    'release Year': 'release_year',
    'genres': 'genres',
    'imdb sc0re': 'imdb_score',
    'imdb v0tes': 'imdb_votes'
}# Rename columns to make them consistent and correct errors

In [6]:
df = df.rename(columns=new_column_names)
df.columns = df.columns.str.strip()# Print the updated column names to confirm changes

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 1</b> 
    
This is a good way to rename the columns.

## Task 2: Correcting a Misspelled Name in the Data

While analyzing the dataset, you notice that some names are misspelled or contain special characters due to encoding issues. Accurate data is essential for reporting and recommendations, so let’s correct one of these entries.

### Instructions

1. **Locate the Row with the Incorrect Name**:
   - Use `.loc[]` to retrieve the row where `name` is `"In??s Prieto"`.
   - You can locate a row based on the index (85576) and column name called "name".
   - Print the row to verify that you have the correct one.


2. **Correct the Name**:
   - Using `.loc[]`, update the `name` column for this row to "Ines Prieto."
   
3. **Verify the Correction**:
   - Print the row again to ensure that the name has been corrected.

In [7]:
incorrect_name_row = df.loc[df['name'] == "In??s Prieto"]
print(incorrect_name_row)# Locate the row with the incorrect name

               name character   role    title       type  release_year  \
77798  In??s Prieto     Fanny  ACTOR  Lokillo      MOVIE          2021
85576  In??s Prieto     Fanny  ACTOR  Lokillo  the movie          2021

           genres  imdb_score  imdb_votes
77798  ['comedy']         3.8        68.0
85576  ['comedy']         3.8        68.0

In [8]:
df.loc[df['name'] == "In??s Prieto", 'name'] = "Ines Prieto"# Correct the name

In [9]:
corrected_row = df.loc[df['name'] == "Ines Prieto"]
print(corrected_row)# Verify the correction

              name character   role    title       type  release_year  \
77798  Ines Prieto     Fanny  ACTOR  Lokillo      MOVIE          2021
85576  Ines Prieto     Fanny  ACTOR  Lokillo  the movie          2021

           genres  imdb_score  imdb_votes
77798  ['comedy']         3.8        68.0
85576  ['comedy']         3.8        68.0

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 1</b> 
    
Perfect!

## Task 3: Finding All Movies and Shows Featuring Ines Prieto

Now that we've corrected the spelling of "Ines Prieto" in the dataset, let's find all the TV shows and movies she has acted in. This type of filtering is helpful for generating actor-specific profiles or building a list of their works.

### Instructions

1. **Filter by Actor’s Name**:
   - Use a filtering condition to select rows where the `name` column is equal to `"Ines Prieto"`.
   
2. **Display Relevant Columns**:
   - From each matching row, retrieve only the `title`, `release_year`, `imdb_score`, and `genres` columns for a clear, concise output.

**Hint:**

To filter rows based on a specific value in a column, use a condition inside df[ ... ]. In this case, check if the name column equals "Ines Prieto". Then, select only the columns you need (like title, release_year, imdb_score, and genres) by specifying them in double brackets [ [ ... ] ].

In [10]:
ines_works = df[df['name'] == "Ines Prieto"][['title', 'release_year', 'imdb_score', 'genres']]# Filter rows where the actor's name is "Ines Prieto" and display the title, release_year, genres, and imdb_score

In [11]:
print(ines_works)# Display the result

         title  release_year  imdb_score      genres
77798  Lokillo          2021         3.8  ['comedy']
85576  Lokillo          2021         3.8  ['comedy']

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 1</b> 
    
You have displayed the required result quite correctly.

<div class="alert alert-warning"; style="border-left: 7px solid gold">
<b>⚠️ Reviewer's comment, v. 1</b> 
    
The result would be shown a little better if you use `display` instead of `print` :)

## Task 4: Finding Highly Rated Movies

We want to identify movies with an IMDb rating of at least **9.0**. This list could be helpful for curating a "Top Movies" section based on high ratings.

### Instructions

1. **Filter for High IMDb Scores**:
   - First, filter the DataFrame to include only rows where the `imdb_score` is greater than 9.0.

2. **Extract the Titles**:
   - From this filtered DataFrame, select only the `title` column, which contains the names of the movies.

3. **Get Unique Titles**:
   - Convert the resulting list of titles to a set to remove any duplicate titles. Using `set()` will keep only unique movie names.

   - *Example*: `unique_titles = set(high_score_titles)`

4. **Print the Unique Titles**:
   - Display the final set of unique movie titles to see the list of top-rated movies.

In [12]:
high_rated_movies = df[(df['imdb_score'] >= 9.0) & (df['type'] == 'MOVIE')]# Filter for movies with an IMDb score above 9.0


unique_titles = set(high_rated_movies['title'])# Extract the 'title' column from the filtered DataFrame


print("Movies with IMDb Score >= 9.0:")# Get a unique set of titles


for title in sorted(unique_titles):
    print(f"• {title}")# Print the unique titles

Movies with IMDb Score >= 9.0:
• Major

<div class="alert alert-danger"; style="border-left: 7px solid red">
<b>⛔️ Reviewer's comment, v. 1</b> 
    
    
Please double check that the above code is running and has no errors.

<div class="alert alert-warning"; style="border-left: 7px solid gold">
<b>⚠️ Reviewer's comment, v. 2</b> 

Please note that according to the assignment, there was no need to add this filtering in the first line of the code. Here, by "movie" we mean all the available data.

    df['type'] == 'MOVIE'

Thank you for revewing the project and commenting with helpful suggestions and recommendations. 
I have found the few inconsistency mistakes such as replacing "and" with &, adding parentheses around each condition and fixing the variable name consistency.

## Task 5: Creating a Function to Find Unique Top-Rated Movies

In this task, we’ll create a function to find unique movies with an IMDb score above a certain threshold that the user provides.

### Instructions

1. **Define the Function**:
   - Start by creating a function called `get_unique_top_movies` that takes one parameter, `min_score`.

2. **Filter the Data**:
   - Inside the function, create a new variable (e.g., `high_score_df`) that stores rows where the `imdb_score` is greater than or equal to `min_score`.

3. **Extract Movie Titles**:
   - In a new variable (e.g., `high_score_titles`), select the `title` column from the filtered DataFrame.

4. **Remove Duplicate Titles**:
   - Convert `high_score_titles` to a set using `set(high_score_titles)` to automatically remove duplicates, ensuring each title appears only once.

5. **Return the Unique Titles**:
   - Make sure the function returns the `unique_titles` set.

In [13]:
# Define the function
def get_unique_top_movies(min_score):
    high_score_df = df[(df['imdb_score'] >= min_score) & (df['type'] == 'MOVIE')]# Filter for movies with IMDb score above min_score


    high_score_titles = high_score_df['title']# Extract the 'title' column


    unique_titles = set(high_score_titles)# Remove duplicate titles


    return unique_titles# Return unique titles

In [14]:
# Test the function
print(get_unique_top_movies(9.0))

{'Major'}

<div class="alert alert-danger"; style="border-left: 7px solid red">
<b>⛔️ Reviewer's comment, v. 1</b> 
    
Please double-check the correct naming of all variables.

<div class="alert alert-warning"; style="border-left: 7px solid gold">
<b>⚠️ Reviewer's comment, v. 2</b> 

In this assignment, there was also no need to add this filtering at the beginning. Here, by "movie" we mean all the available data.

    df['type'] == 'MOVIE'

## Task 6: Creating a Function to Find Top Movies from a Specific Decade

Let’s create a function to retrieve movies from a particular decade with high IMDb ratings. This function can be useful for generating lists of top-rated movies from different time periods.

### Instructions

1. **Define the Function**:
   - Create a function called `get_top_movies_from_decade` that accepts `decade_start` and `min_score` as parameters.

2. **Filter by Decade**:
   - Inside the function, filter the DataFrame to include only movies where `release_year` is within the specified decade.
   - *Hint*: You can achieve this by checking that `release_year` is between `decade_start` and `decade_start + 9`

3. **Filter by IMDb Score**:
   - Further filter this subset to include only movies where `imdb_score` is greater than or equal to `min_score`.

4. **Extract Movie Titles**:
   - From the resulting DataFrame, select the `title` column and remove duplicates using set().

5. **Return the List of Titles**:
   - Return the set of the best movies from that decade.

By completing this task, you’ll have a function that returns unique, top-rated movies from a specified decade. This is useful for highlighting standout movies from different eras, perfect for “Best of the Decade” features!

In [15]:
# Define the function
def get_top_movies_from_decade(decade_start, min_score):
    decade_movies = df[
        (df['release_year'] >= decade_start) &
        (df['release_year'] <= decade_start + 9) &
        (df['imdb_score'] >= min_score) &
        (df['type'] == 'MOVIE')
    ]# Filter for movies released within the decade # Further filter by IMDb score


    unique_titles = set(decade_movies['title'])# Extract and remove duplicate titles


    return unique_titles # Return unique titles

In [16]:
# Test the function
print(get_top_movies_from_decade(1990, 8.5))

{'Forrest Gump', 'L??on: The Professional', 'Bill Hicks: Revelations', 'GoodFellas', 'Se7en'}

<div class="alert alert-danger"; style="border-left: 7px solid red">
<b>⛔️ Reviewer's comment, v. 1</b> 
    
Please double-check whether all filtering is defined correctly in the function.

<div class="alert alert-warning"; style="border-left: 7px solid gold">
<b>⚠️ Reviewer's comment, v. 2</b> 

And once again there was also no need to add this filtering at the beginning. 

    df['type'] == 'MOVIE'

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 2</b> 
    
Otherwise, all the tasks above were completed absolutely correctly.


## Task 7: Creating a Function to List All Actors in a Given Title

Imagine you want to list all the actors in a specific movie or show. Let’s create a function that takes a `title` as input and returns the names of all actors in that title, combined into a single string.


### Instructions

1. **Define the Function**:
   - Create a function called `get_actors_for_title` that accepts one parameter, `title`.
   
2. **Filter by Title and Role**:
   - Inside the function, filter the DataFrame to select rows where the `title` column matches the provided `title` parameter and the `role` column is `"ACTOR"` (to ensure you only retrieve actors).

3. **Extract Actor Names**:
   - From this filtered DataFrame, select only the `name` column to get the actor names.

4. **Combine Names into a Single String**:
   - Use `', '.join()` to combine the list of actor names into a single string, with each name separated by a comma.

5. **Return the Result**:
   - Return the resulting string of actor names.


This function will allow you to retrieve and format a list of actors for any movie or show title, which is useful for creating cast lists or displaying actors for specific titles.

In [17]:
# Define the function
def get_actors_for_title(title):
    actors_df = df[(df['title'] == title) & (df['role'] == 'ACTOR')]# Filter for rows with the specified title and role as 'ACTOR'


    actor_names = actors_df['name']
    
    if len(actor_names) == 0:
        return f"No actors found for '{title}'"


    return ', '.join(actor_names)

In [18]:
# Test the function
print(get_actors_for_title("Taxi Driver"))

Robert De Niro, Jodie Foster, Albert Brooks, Harvey Keitel, Cybill Shepherd, Peter Boyle, Leonard Harris, Diahnne Abbott, Gino Ardito, Martin Scorsese, Murray Moston, Richard Higgs, Bill Minkin, Bob Maroff, Victor Argo, Joe Spinell, Robinson Frank Adu, Brenda Dickson, Norman Matlock, Harry Northup, Harlan Cary Poe, Steven Prince, Peter Savage, Nicholas Shields, Ralph S. Singleton, Annie Gagen, Carson Grant, Mary-Pat Green, Debbi Morgan, Don Stroud, Copper Cunningham, Garth Avery, Nat Grant, Billie Perkins, Catherine Scorsese, Charles Scorsese, Odunlade Adekola, Ijeoma Grace Agu

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 1</b> 
    
You used `join` correctly in your function.

## Task 8: Creating a Function to Categorize Movies by IMDb Score

Let’s categorize movies and shows based on their IMDb scores to provide a quick evaluation of their popularity or quality. We’ll create a function that takes in a `title` and returns a rating category based on the movie or show’s IMDb score.

### Rating Categories

- **Excellent**: IMDb score of 9.0 or higher
- **Good**: IMDb score between 7.0 and 8.9
- **Average**: IMDb score between 5.0 and 6.9
- **Low**: IMDb score below 5.0

### Instructions

1. **Define the Function**:
   - Create a function called `categorize_imdb_score` that accepts one parameter, `title`.

2. **Filter by Title**:
   - Inside the function, filter the DataFrame to find the row where `title` matches the given title.

3. **Retrieve IMDb Score**:
   - If the title exists, retrieve the `imdb_score` for that movie or show.
   - If the title is not found, return `"Title not found"`.

4. **Categorize Score with `if-else`**:
   - Use `if-elif-else` statements to evaluate the `imdb_score` and return one of the rating categories based on the ranges provided.

5. **Return the Category**:
   - Return the appropriate category based on the score.

This function allows you to quickly categorize movies or shows by their IMDb score, which could be helpful for creating rating tags or recommending top-rated content.

In [19]:
# Define the function
def categorize_imdb_score(title):
    title_data = df[df['title'].str.lower() == title.lower()]# Filter for the row with the specified title

    if len(title_data) == 0:
        return "Title not found"# Check if title exists


    score = title_data.iloc[0]['imdb_score']
    
    if pd.isna(score):
        return "No IMDb score available"# Retrieve the IMDb score for the movie


    if score >= 9.0:
        return "Excellent"
    elif score >= 7.0:
        return "Good"
    elif score >= 5.0:
        return "Average"
    else: 
        return "Low"# Categorize score using if-else and return the ranking accordingly

In [20]:
# Test the function
print(categorize_imdb_score("Taxi Driver"))

Good

<div class="alert alert-danger"; style="border-left: 7px solid red">
<b>⛔️ Reviewer's comment, v. 1</b> 
    
Please double-check whether all conditions are defined correctly in the function.

<div class="alert alert-success"; style="border-left: 7px solid green">
<b>✅ Reviewer's comment, v. 2</b> 
    
Great!

Now all conditions are correctly defined such as title existence score abailabilty and rating categories. I also fexed spacings, colons, and properly aligned all code blocks with consistent identation.